---

default: true

# MD013 - Line length
# 长度检测太烦了，索性关闭
line_length: false
#MD013:
#  line_length: 120
#  code_blocks: false

# MD024 - Multiple headers with the same content
MD024:
  allow_different_nesting: true

# MD029 - Ordered list item prefix
#style: ordered
