name: Markdown-Lint

on: 
  push:
    branches: master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        config_file: .markdownlint.yaml
        files: .
        ignore_files: "README.md"
